# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Utility

class Ui_MainWindow(object):
    def setupUi(self, MainWindow,MainWindow2,MainWindow3):
        self.MainWindow = MainWindow
        self.MainWindow2 = MainWindow2
        self.MainWindow3 = MainWindow3
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(300, 100))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.b2)
        self.gridLayout.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.b1)
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.b3)
        self.gridLayout.addWidget(self.pushButton_3, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.checkInternetAtStart()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "Control"))
        self.pushButton.setText(_translate("MainWindow", "Config"))
        self.pushButton_3.setText(_translate("MainWindow", "Restart connection"))

    def checkInternetAtStart(self):
        camera1status=Utility.camera1_on()
        camera2status=Utility.camera2_on()
        if camera1status and camera2status:
            self.label.setText("Connected")
            self.pushButton_3.hide()
        elif camera1status and camera2status == False:
            self.label.setText("camera 2 offline, check camera connection")
            #add a new button to try to connect again
        elif camera1status == False and camera2status :
            self.label.setText("camera 1 offline, check camera connection")
        else:
            self.label.setText("both cameras offline, check  WiFi connection")

    def b1(self):
        print("Pressed show config gui")
        self.MainWindow2.show()

    def b2(self):
        print("Pressed show control gui")
        self.MainWindow3.show()


    def b3(self):
        print("Pressed restart connection")
        self.checkInternetAtStart()